ALTER TABLE user ADD COLUMN blocks_broken INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user ADD COLUMN blocks_placed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user ADD COLUMN play_time INTEGER NOT NULL DEFAULT 0;
