ALTER TABLE user ADD COLUMN messages_sent INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user ADD COLUMN commands_executed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user ADD COLUMN enemies_killed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user ADD COLUMN waves_survived INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user ADD COLUMN afk_time INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user ADD COLUMN blocks_destroyed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user ADD COLUMN deaths INTEGER NOT NULL DEFAULT 0;
